<?php

namespace App\Filament\Resources\Homepages\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Tables\Columns\IconColumn;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class HomepagesTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('hero_title')
                    ->searchable(),
                TextColumn::make('hero_tab_1_label')
                    ->searchable(),
                TextColumn::make('hero_tab_2_label')
                    ->searchable(),
                TextColumn::make('hero_tab_3_label')
                    ->searchable(),
                TextColumn::make('about_section_label')
                    ->searchable(),
                TextColumn::make('about_title')
                    ->searchable(),
                TextColumn::make('about_button_text')
                    ->searchable(),
                TextColumn::make('about_button_link')
                    ->searchable(),
                TextColumn::make('global_section_title')
                    ->searchable(),
                TextColumn::make('global_section_subtitle')
                    ->searchable(),
                TextColumn::make('card_1_title')
                    ->searchable(),
                TextColumn::make('card_2_title')
                    ->searchable(),
                TextColumn::make('card_3_title')
                    ->searchable(),
                TextColumn::make('card_4_title')
                    ->searchable(),
                TextColumn::make('stat_1_label')
                    ->searchable(),
                TextColumn::make('stat_1_value')
                    ->searchable(),
                TextColumn::make('stat_2_label')
                    ->searchable(),
                TextColumn::make('stat_2_value')
                    ->searchable(),
                TextColumn::make('stat_3_label')
                    ->searchable(),
                TextColumn::make('stat_3_value')
                    ->searchable(),
                TextColumn::make('stat_4_label')
                    ->searchable(),
                TextColumn::make('stat_4_value')
                    ->searchable(),
                TextColumn::make('partners_title')
                    ->searchable(),
                TextColumn::make('insights_section_label')
                    ->searchable(),
                TextColumn::make('insights_title')
                    ->searchable(),
                TextColumn::make('insights_button_text')
                    ->searchable(),
                TextColumn::make('insights_button_link')
                    ->searchable(),
                TextColumn::make('insights_background_color')
                    ->searchable(),
                TextColumn::make('testimonials_title')
                    ->searchable(),
                TextColumn::make('careers_section_label')
                    ->searchable(),
                TextColumn::make('careers_title')
                    ->searchable(),
                TextColumn::make('careers_subtitle')
                    ->searchable(),
                TextColumn::make('careers_button_text')
                    ->searchable(),
                TextColumn::make('careers_button_link')
                    ->searchable(),
                TextColumn::make('careers_background_color')
                    ->searchable(),
                TextColumn::make('featured_section_title')
                    ->searchable(),
                IconColumn::make('show_off_plan_tab')
                    ->boolean(),
                IconColumn::make('show_buy_tab')
                    ->boolean(),
                IconColumn::make('show_rent_tab')
                    ->boolean(),
                IconColumn::make('show_commercial_tab')
                    ->boolean(),
                IconColumn::make('show_featured_projects_tab')
                    ->boolean(),
                TextColumn::make('properties_per_section')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('contact_section_label')
                    ->searchable(),
                TextColumn::make('contact_title')
                    ->searchable(),
                TextColumn::make('contact_title_highlight')
                    ->searchable(),
                TextColumn::make('contact_form_name_placeholder')
                    ->searchable(),
                TextColumn::make('contact_form_email_placeholder')
                    ->searchable(),
                TextColumn::make('contact_form_phone_placeholder')
                    ->searchable(),
                TextColumn::make('contact_form_interest_placeholder')
                    ->searchable(),
                TextColumn::make('contact_form_message_placeholder')
                    ->searchable(),
                TextColumn::make('contact_form_button_text')
                    ->searchable(),
                TextColumn::make('newsletter_section_label')
                    ->searchable(),
                TextColumn::make('newsletter_title')
                    ->searchable(),
                TextColumn::make('newsletter_firstname_placeholder')
                    ->searchable(),
                TextColumn::make('newsletter_lastname_placeholder')
                    ->searchable(),
                TextColumn::make('newsletter_email_placeholder')
                    ->searchable(),
                TextColumn::make('newsletter_button_text')
                    ->searchable(),
                TextColumn::make('newsletter_background_color')
                    ->searchable(),
                TextColumn::make('meta_title')
                    ->searchable(),
                TextColumn::make('meta_keywords')
                    ->searchable(),
                TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
